export const LOAD_CASES_START = 'LOAD_CASES_START';
export const LOAD_CASES_SUCCESS = 'LOAD_CASES_SUCCESS';
export const LOAD_CASES_FAIL = 'LOAD_CASES_FAIL';
export const FILTER_BY_TITLE = 'FILTER_BY_TITLE';
